name: ket_studio
description: "KET Studio — production-grade quantum engineering workbench."
publish_to: 'none'
version: 0.3.0-dev.2+3

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_highlight: ^0.7.0
  google_fonts: ^6.3.3
  code_text_field: ^1.1.0
  flutter_code_editor: ^0.3.5
  file_picker: ^10.3.7
  path_provider: ^2.1.5
  path: ^1.9.1
  process_run: ^1.2.4
  multi_split_view: ^3.6.1
  fluent_ui: ^4.12.0
  window_manager: ^0.5.1
  flutter_acrylic: ^1.1.4
  highlight: ^0.7.0
  shared_preferences: ^2.5.4
  flutter_math_fork: ^0.7.4
  xterm3: ^6.3.0
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.7

msix_config:
  display_name: KET Studio
  publisher_display_name: AxionSoftware
  msix_version: 0.3.0.2
  logo_path: assets/quantum.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/quantum.jpg"
  windows:
    generate: true
    image_path: "assets/quantum.jpg"
    icon_size: 48

flutter:
  uses-material-design: false
  assets:
    - assets/quantum.jpg
    - runtime/python/ket_kernel.py
